apiVersion: v1
kind: ConfigMap
metadata:
    name: aws-auth
    namespace: kube-system
data:
    mapRoles: |
        - rolearn: arn:aws:iam::451676855697:role/BlueGreen-Kubernetes-Role
          username: system:node:{{EC2PrivateDNSName}}
          groups:
            - system:bootstrappers
            - system:nodes
    mapUsers: |
        - userarn: arn:aws:iam::451676855697:user/KubernetesAdmin
          username: KubernetesAdmin
          groups:
            - system:masters